#!/usr/bin/env python3
"""Write LearnDSA problem JSON files."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1] / "content" / "problems"
ROOT.mkdir(parents=True, exist_ok=True)


def py_fn(name: str, params: list[tuple[str, str]], ret: str) -> str:
    args = ", ".join(f"{n}: {t}" for n, t in params)
    return f"class Solution:\n    def {name}(self, {args}) -> {ret}:\n        pass\n"


def js_fn(name: str, params: list[tuple[str, str]], ret: str) -> str:
    lines = ["/**"]
    for n, t in params:
        lines.append(f" * @param {{{t}}} {n}")
    lines.append(f" * @return {{{ret}}}")
    lines.append(" */")
    args = ", ".join(n for n, _ in params)
    lines.append(f"var {name} = function({args}) {{\n    \n}};")
    return "\n".join(lines) + "\n"


def dump(p: dict) -> None:
    path = ROOT / f"{p['id']}.json"
    path.write_text(json.dumps(p, indent=2) + "\n")


def P(
    *,
    id: str,
    title: str,
    difficulty: str,
    tags: list[str],
    unitId: str,
    kind: str,
    order: int,
    microsoftNote: str,
    statement: str,
    examples: list,
    constraints: list[str],
    followUp: str | None,
    editorial: str,
    entry: str,
    paramNames: list[str],
    helpers: list[str],
    py_params: list[tuple[str, str]],
    py_ret: str,
    js_params: list[tuple[str, str]],
    js_ret: str,
    visible: list,
    hidden: list,
    mode: str = "function",
    starter_py: str | None = None,
    starter_js: str | None = None,
) -> None:
    dump(
        {
            "id": id,
            "title": title,
            "difficulty": difficulty,
            "tags": tags,
            "unitId": unitId,
            "kind": kind,
            "order": order,
            "microsoftNote": microsoftNote,
            "statement": statement,
            "examples": examples,
            "constraints": constraints,
            "followUp": followUp,
            "editorial": editorial,
            "mode": mode,
            "entry": {"python": entry, "javascript": entry},
            "paramNames": paramNames,
            "helpers": helpers,
            "starter": {
                "python": starter_py or py_fn(entry, py_params, py_ret),
                "javascript": starter_js or js_fn(entry, js_params, js_ret),
            },
            "tests": {"visible": visible, "hidden": hidden},
        }
    )


def main() -> None:
    P(
        id="two-sum",
        title="Two Sum",
        difficulty="easy",
        tags=["Array", "Hash Map"],
        unitId="unit-01",
        kind="core",
        order=1,
        microsoftNote="OA staple. One-pass hash map is the expected story, not the nested loop.",
        statement="Given an array of integers `nums` and an integer `target`, return **the indices** of the two numbers that add up to `target`.\n\nYou may assume each input has **exactly one** solution, and you may not use the same element twice. Return the indices in any order.",
        examples=[
            {"input": "nums = [2,7,11,15], target = 9", "output": "[0,1]", "explanation": "nums[0] + nums[1] = 2 + 7 = 9."},
            {"input": "nums = [3,2,4], target = 6", "output": "[1,2]"},
        ],
        constraints=["2 <= nums.length <= 10^4", "-10^9 <= nums[i] <= 10^9", "-10^9 <= target <= 10^9", "Exactly one valid answer exists."],
        followUp="Can you do it in one pass?",
        editorial="Walk the array once. For each value x, look up target - x in a map of value → index. If it exists, return those indices. Otherwise store x.",
        entry="twoSum",
        paramNames=["nums", "target"],
        helpers=["json", "json", "json"],
        py_params=[("nums", "list[int]"), ("target", "int")],
        py_ret="list[int]",
        js_params=[("nums", "number[]"), ("target", "number")],
        js_ret="number[]",
        visible=[
            {"args": {"nums": [2, 7, 11, 15], "target": 9}, "expected": [0, 1], "compare": "sorted"},
            {"args": {"nums": [3, 2, 4], "target": 6}, "expected": [1, 2], "compare": "sorted"},
        ],
        hidden=[
            {"args": {"nums": [3, 3], "target": 6}, "expected": [0, 1], "compare": "sorted"},
            {"args": {"nums": [0, 4, 3, 0], "target": 0}, "expected": [0, 3], "compare": "sorted"},
            {"args": {"nums": [-1, -2, -3, -4, -5], "target": -8}, "expected": [2, 4], "compare": "sorted"},
        ],
    )

    P(
        id="contains-duplicate",
        title="Contains Duplicate",
        difficulty="easy",
        tags=["Array", "Hash Map"],
        unitId="unit-01",
        kind="core",
        order=2,
        microsoftNote="Warm-up used to see if you reach for a set without being asked.",
        statement="Given an integer array `nums`, return `true` if any value appears **at least twice**, and `false` if every element is distinct.",
        examples=[
            {"input": "nums = [1,2,3,1]", "output": "true"},
            {"input": "nums = [1,2,3,4]", "output": "false"},
        ],
        constraints=["1 <= nums.length <= 10^5", "-10^9 <= nums[i] <= 10^9"],
        followUp="What is the time/space trade-off versus sorting?",
        editorial="Insert into a hash set while iterating. If an insert is a duplicate, return true. Sorting is O(n log n) extra-time, O(1) extra-space.",
        entry="containsDuplicate",
        paramNames=["nums"],
        helpers=["json", "json"],
        py_params=[("nums", "list[int]")],
        py_ret="bool",
        js_params=[("nums", "number[]")],
        js_ret="boolean",
        visible=[
            {"args": {"nums": [1, 2, 3, 1]}, "expected": True},
            {"args": {"nums": [1, 2, 3, 4]}, "expected": False},
        ],
        hidden=[
            {"args": {"nums": [1, 1, 1, 3, 3, 4, 3, 2, 4, 2]}, "expected": True},
            {"args": {"nums": [0]}, "expected": False},
        ],
    )

    P(
        id="best-time-buy-sell",
        title="Best Time to Buy and Sell Stock",
        difficulty="easy",
        tags=["Array", "Greedy"],
        unitId="unit-01",
        kind="core",
        order=3,
        microsoftNote="One-pass min-so-far. Interviewers watch whether you invent O(n^2) first and then cut it.",
        statement="You are given `prices` where `prices[i]` is the price of a stock on day `i`.\n\nYou want one buy and one later sell. Return the maximum profit. If you cannot profit, return `0`.",
        examples=[
            {"input": "prices = [7,1,5,3,6,4]", "output": "5", "explanation": "Buy on day 2 (1) and sell on day 5 (6)."},
            {"input": "prices = [7,6,4,3,1]", "output": "0"},
        ],
        constraints=["1 <= prices.length <= 10^5", "0 <= prices[i] <= 10^4"],
        followUp="What if you could complete at most two transactions?",
        editorial="Track the minimum price seen so far and the best `price - min` as you scan once.",
        entry="maxProfit",
        paramNames=["prices"],
        helpers=["json", "json"],
        py_params=[("prices", "list[int]")],
        py_ret="int",
        js_params=[("prices", "number[]")],
        js_ret="number",
        visible=[
            {"args": {"prices": [7, 1, 5, 3, 6, 4]}, "expected": 5},
            {"args": {"prices": [7, 6, 4, 3, 1]}, "expected": 0},
        ],
        hidden=[
            {"args": {"prices": [2, 4, 1]}, "expected": 2},
            {"args": {"prices": [3, 2, 6, 5, 0, 3]}, "expected": 4},
            {"args": {"prices": [1]}, "expected": 0},
        ],
    )

    P(
        id="valid-anagram",
        title="Valid Anagram",
        difficulty="easy",
        tags=["String", "Hash Map"],
        unitId="unit-01",
        kind="core",
        order=4,
        microsoftNote="Frequency maps. Unicode follow-up is a chance to talk constraints.",
        statement="Given two strings `s` and `t`, return `true` if `t` is an anagram of `s`, and `false` otherwise.\n\nAn anagram uses the same characters the same number of times.",
        examples=[
            {"input": 's = "anagram", t = "nagaram"', "output": "true"},
            {"input": 's = "rat", t = "car"', "output": "false"},
        ],
        constraints=["1 <= s.length, t.length <= 5 * 10^4", "s and t consist of lowercase English letters."],
        followUp="What if the inputs contained Unicode characters?",
        editorial="Count characters in s, decrement with t. All counts must land on zero. Sorting both is the slower alternative.",
        entry="isAnagram",
        paramNames=["s", "t"],
        helpers=["json", "json", "json"],
        py_params=[("s", "str"), ("t", "str")],
        py_ret="bool",
        js_params=[("s", "string"), ("t", "string")],
        js_ret="boolean",
        visible=[
            {"args": {"s": "anagram", "t": "nagaram"}, "expected": True},
            {"args": {"s": "rat", "t": "car"}, "expected": False},
        ],
        hidden=[
            {"args": {"s": "a", "t": "a"}, "expected": True},
            {"args": {"s": "ab", "t": "a"}, "expected": False},
            {"args": {"s": "aa", "t": "a"}, "expected": False},
        ],
    )

    P(
        id="group-anagrams",
        title="Group Anagrams",
        difficulty="medium",
        tags=["String", "Hash Map"],
        unitId="unit-01",
        kind="stretch",
        order=5,
        microsoftNote="Map from a canonical key (sorted letters or 26-count tuple) to a list of words.",
        statement="Given an array of strings `strs`, group the anagrams together. Return the groups in any order.",
        examples=[{"input": 'strs = ["eat","tea","tan","ate","nat","bat"]', "output": '[["bat"],["nat","tan"],["ate","eat","tea"]]'}],
        constraints=["1 <= strs.length <= 10^4", "0 <= strs[i].length <= 100", "strs[i] consists of lowercase English letters."],
        followUp="Can you avoid sorting each word?",
        editorial="Key = sorted word, or a 26-length count tuple. Bucket strings by key.",
        entry="groupAnagrams",
        paramNames=["strs"],
        helpers=["json", "json"],
        py_params=[("strs", "list[str]")],
        py_ret="list[list[str]]",
        js_params=[("strs", "string[]")],
        js_ret="string[][]",
        visible=[
            {"args": {"strs": ["eat", "tea", "tan", "ate", "nat", "bat"]}, "expected": [["bat"], ["nat", "tan"], ["ate", "eat", "tea"]], "compare": "set"},
        ],
        hidden=[
            {"args": {"strs": [""]}, "expected": [[""]], "compare": "set"},
            {"args": {"strs": ["a"]}, "expected": [["a"]], "compare": "set"},
        ],
    )

    # Unit 2
    P(
        id="valid-palindrome",
        title="Valid Palindrome",
        difficulty="easy",
        tags=["String", "Two Pointers"],
        unitId="unit-02",
        kind="core",
        order=1,
        microsoftNote="Two pointers skipping non-alphanumeric. Off-by-one on empty leftover.",
        statement="A phrase is a palindrome if, after converting all uppercase letters into lowercase and removing all non-alphanumeric characters, it reads the same forward and backward.\n\nGiven a string `s`, return `true` if it is a palindrome.",
        examples=[
            {"input": 's = "A man, a plan, a canal: Panama"', "output": "true"},
            {"input": 's = "race a car"', "output": "false"},
        ],
        constraints=["1 <= s.length <= 2 * 10^5", "s consists of printable ASCII."],
        followUp="Do it with O(1) extra memory.",
        editorial="Left and right pointers. Skip non-alnum, compare lowercased chars, move inward.",
        entry="isPalindrome",
        paramNames=["s"],
        helpers=["json", "json"],
        py_params=[("s", "str")],
        py_ret="bool",
        js_params=[("s", "string")],
        js_ret="boolean",
        visible=[
            {"args": {"s": "A man, a plan, a canal: Panama"}, "expected": True},
            {"args": {"s": "race a car"}, "expected": False},
        ],
        hidden=[
            {"args": {"s": " "}, "expected": True},
            {"args": {"s": "0P"}, "expected": False},
            {"args": {"s": "ab_a"}, "expected": True},
        ],
    )

    P(
        id="container-most-water",
        title="Container With Most Water",
        difficulty="medium",
        tags=["Array", "Two Pointers", "Greedy"],
        unitId="unit-02",
        kind="core",
        order=2,
        microsoftNote="Classic two-pointer greedy. Prove why you move the shorter side.",
        statement="You are given `height` of length `n`. Two indices `i < j` form a container of area `min(height[i], height[j]) * (j - i)`.\n\nReturn the maximum area of water the container can store.",
        examples=[{"input": "height = [1,8,6,2,5,4,8,3,7]", "output": "49"}],
        constraints=["n == height.length", "2 <= n <= 10^5", "0 <= height[i] <= 10^4"],
        followUp="Why is the two-pointer algorithm correct?",
        editorial="Start at both ends. Area is limited by the shorter line. Move that pointer inward; the width shrinks, so the only way to improve is a taller min.",
        entry="maxArea",
        paramNames=["height"],
        helpers=["json", "json"],
        py_params=[("height", "list[int]")],
        py_ret="int",
        js_params=[("height", "number[]")],
        js_ret="number",
        visible=[
            {"args": {"height": [1, 8, 6, 2, 5, 4, 8, 3, 7]}, "expected": 49},
            {"args": {"height": [1, 1]}, "expected": 1},
        ],
        hidden=[
            {"args": {"height": [4, 3, 2, 1, 4]}, "expected": 16},
            {"args": {"height": [1, 2, 1]}, "expected": 2},
        ],
    )

    P(
        id="longest-substring-no-repeat",
        title="Longest Substring Without Repeating Characters",
        difficulty="medium",
        tags=["String", "Sliding Window", "Hash Map"],
        unitId="unit-02",
        kind="core",
        order=3,
        microsoftNote="Variable window. Microsoft likes this as a communication problem: when does the left pointer move?",
        statement="Given a string `s`, find the length of the longest substring without repeating characters.",
        examples=[
            {"input": 's = "abcabcbb"', "output": "3", "explanation": '"abc"'},
            {"input": 's = "bbbbb"', "output": "1"},
        ],
        constraints=["0 <= s.length <= 5 * 10^4", "s consists of English letters, digits, symbols and spaces."],
        followUp="What if the alphabet is huge?",
        editorial="Window [left, right]. Map char → last index. If s[right] was seen at or after left, jump left. Track max width.",
        entry="lengthOfLongestSubstring",
        paramNames=["s"],
        helpers=["json", "json"],
        py_params=[("s", "str")],
        py_ret="int",
        js_params=[("s", "string")],
        js_ret="number",
        visible=[
            {"args": {"s": "abcabcbb"}, "expected": 3},
            {"args": {"s": "bbbbb"}, "expected": 1},
            {"args": {"s": "pwwkew"}, "expected": 3},
        ],
        hidden=[
            {"args": {"s": ""}, "expected": 0},
            {"args": {"s": " "}, "expected": 1},
            {"args": {"s": "dvdf"}, "expected": 3},
            {"args": {"s": "abba"}, "expected": 2},
        ],
    )

    P(
        id="min-size-subarray-sum",
        title="Minimum Size Subarray Sum",
        difficulty="medium",
        tags=["Array", "Sliding Window"],
        unitId="unit-02",
        kind="core",
        order=4,
        microsoftNote="Positive integers make a shrinking window valid. Say that out loud.",
        statement="Given an array of **positive** integers `nums` and a positive integer `target`, return the **minimal length** of a subarray whose sum is greater than or equal to `target`. If none exists, return `0`.",
        examples=[{"input": "target = 7, nums = [2,3,1,2,4,3]", "output": "2", "explanation": "[4,3]"}],
        constraints=["1 <= target <= 10^9", "1 <= nums.length <= 10^5", "1 <= nums[i] <= 10^4"],
        followUp="O(n) time, O(1) extra space.",
        editorial="Expand right, add. While sum >= target, record length and subtract nums[left], then left++.",
        entry="minSubArrayLen",
        paramNames=["target", "nums"],
        helpers=["json", "json", "json"],
        py_params=[("target", "int"), ("nums", "list[int]")],
        py_ret="int",
        js_params=[("target", "number"), ("nums", "number[]")],
        js_ret="number",
        visible=[
            {"args": {"target": 7, "nums": [2, 3, 1, 2, 4, 3]}, "expected": 2},
            {"args": {"target": 4, "nums": [1, 4, 4]}, "expected": 1},
        ],
        hidden=[
            {"args": {"target": 11, "nums": [1, 1, 1, 1, 1, 1, 1, 1]}, "expected": 0},
            {"args": {"target": 15, "nums": [1, 2, 3, 4, 5]}, "expected": 5},
        ],
    )

    P(
        id="three-sum",
        title="3Sum",
        difficulty="medium",
        tags=["Array", "Two Pointers"],
        unitId="unit-02",
        kind="stretch",
        order=5,
        microsoftNote="Sort, then two-sum on the remainder. Dedup is the part people fumble.",
        statement="Given an integer array `nums`, return all the triplets `[nums[i], nums[j], nums[k]]` such that `i`, `j`, and `k` are distinct and `nums[i] + nums[j] + nums[k] == 0`.\n\nThe solution set must not contain duplicate triplets.",
        examples=[{"input": "nums = [-1,0,1,2,-1,-4]", "output": "[[-1,-1,2],[-1,0,1]]"}],
        constraints=["3 <= nums.length <= 3000", "-10^5 <= nums[i] <= 10^5"],
        followUp="How do you skip duplicates without a set of tuples?",
        editorial="Sort. For each i, two-pointer the rest. Skip equal nums[i], and skip equal left/right after a hit.",
        entry="threeSum",
        paramNames=["nums"],
        helpers=["json", "json"],
        py_params=[("nums", "list[int]")],
        py_ret="list[list[int]]",
        js_params=[("nums", "number[]")],
        js_ret="number[][]",
        visible=[
            {"args": {"nums": [-1, 0, 1, 2, -1, -4]}, "expected": [[-1, -1, 2], [-1, 0, 1]], "compare": "set"},
            {"args": {"nums": [0, 1, 1]}, "expected": [], "compare": "set"},
        ],
        hidden=[
            {"args": {"nums": [0, 0, 0]}, "expected": [[0, 0, 0]], "compare": "set"},
            {"args": {"nums": [-2, 0, 1, 1, 2]}, "expected": [[-2, 0, 2], [-2, 1, 1]], "compare": "set"},
        ],
    )

    write_unit3()
    write_unit4()
    write_unit5()
    write_unit6()
    write_unit7()
    write_unit8()
    write_unit9()
    write_unit10()
    print("wrote", len(list(ROOT.glob('*.json'))), "problems")


def write_unit3() -> None:
    P(
        id="reverse-linked-list",
        title="Reverse Linked List",
        difficulty="easy",
        tags=["Linked List"],
        unitId="unit-03",
        kind="core",
        order=1,
        microsoftNote="Iterative three-pointer reverse. Also have the recursive version ready.",
        statement="Given the head of a singly linked list, reverse the list and return the new head.\n\nThe judge passes arrays; they are converted to `ListNode` for you.",
        examples=[{"input": "head = [1,2,3,4,5]", "output": "[5,4,3,2,1]"}],
        constraints=["The number of nodes is in [0, 5000].", "-5000 <= Node.val <= 5000"],
        followUp="Reverse it both iteratively and recursively.",
        editorial="prev = None. While head: nxt = head.next; head.next = prev; prev = head; head = nxt. Return prev.",
        entry="reverseList",
        paramNames=["head"],
        helpers=["list", "list"],
        py_params=[("head", "Optional[ListNode]")],
        py_ret="Optional[ListNode]",
        js_params=[("head", "ListNode|null")],
        js_ret="ListNode|null",
        visible=[
            {"args": {"head": [1, 2, 3, 4, 5]}, "expected": [5, 4, 3, 2, 1]},
            {"args": {"head": [1, 2]}, "expected": [2, 1]},
        ],
        hidden=[
            {"args": {"head": []}, "expected": []},
            {"args": {"head": [1]}, "expected": [1]},
        ],
    )
    P(
        id="linked-list-cycle",
        title="Linked List Cycle",
        difficulty="easy",
        tags=["Linked List", "Two Pointers"],
        unitId="unit-03",
        kind="core",
        order=2,
        microsoftNote="Floyd. `pos` is the index where the tail connects, or -1.",
        statement="Given `head` of a linked list, return `true` if there is a cycle.\n\nThe test extra field `pos` is the index the tail links to (`-1` if none). You will receive a real `ListNode` that may contain that cycle. Do not use extra O(n) memory if you can help it.",
        examples=[{"input": "head = [3,2,0,-4], pos = 1", "output": "true"}],
        constraints=["The number of nodes is in [0, 10^4].", "-10^5 <= Node.val <= 10^5", "pos is -1 or a valid index."],
        followUp="O(1) extra space.",
        editorial="Slow and fast pointers. If they meet, there is a cycle.",
        entry="hasCycle",
        paramNames=["head"],
        helpers=["json", "list"],
        py_params=[("head", "Optional[ListNode]")],
        py_ret="bool",
        js_params=[("head", "ListNode|null")],
        js_ret="boolean",
        visible=[
            {"args": {"head": [3, 2, 0, -4]}, "extra": {"pos": 1}, "expected": True},
            {"args": {"head": [1, 2]}, "extra": {"pos": 0}, "expected": True},
            {"args": {"head": [1]}, "extra": {"pos": -1}, "expected": False},
        ],
        hidden=[
            {"args": {"head": []}, "extra": {"pos": -1}, "expected": False},
            {"args": {"head": [1, 2, 3, 4]}, "extra": {"pos": -1}, "expected": False},
        ],
    )
    P(
        id="merge-two-sorted-lists",
        title="Merge Two Sorted Lists",
        difficulty="easy",
        tags=["Linked List"],
        unitId="unit-03",
        kind="core",
        order=3,
        microsoftNote="Dummy head. Do not drop the remainder of the longer list.",
        statement="Merge two sorted linked lists and return it as a sorted list. The lists should be spliced together, not copied as new nodes if you can reuse them.",
        examples=[{"input": "list1 = [1,2,4], list2 = [1,3,4]", "output": "[1,1,2,3,4,4]"}],
        constraints=["The number of nodes in both lists is in the range [0, 50].", "-100 <= Node.val <= 100", "Both lists are sorted in non-decreasing order."],
        followUp=None,
        editorial="Dummy node. Always attach the smaller of list1/list2. Append whatever remains.",
        entry="mergeTwoLists",
        paramNames=["list1", "list2"],
        helpers=["list", "list", "list"],
        py_params=[("list1", "Optional[ListNode]"), ("list2", "Optional[ListNode]")],
        py_ret="Optional[ListNode]",
        js_params=[("list1", "ListNode|null"), ("list2", "ListNode|null")],
        js_ret="ListNode|null",
        visible=[
            {"args": {"list1": [1, 2, 4], "list2": [1, 3, 4]}, "expected": [1, 1, 2, 3, 4, 4]},
            {"args": {"list1": [], "list2": []}, "expected": []},
        ],
        hidden=[
            {"args": {"list1": [], "list2": [0]}, "expected": [0]},
            {"args": {"list1": [2], "list2": [1]}, "expected": [1, 2]},
        ],
    )
    P(
        id="valid-parentheses",
        title="Valid Parentheses",
        difficulty="easy",
        tags=["String", "Stack"],
        unitId="unit-03",
        kind="core",
        order=4,
        microsoftNote="Stack matching. Empty stack at the end, never pop empty.",
        statement="Given a string `s` containing just the characters `'('`, `')'`, `'{'`, `'}'`, `'['` and `']'`, determine if the input string is valid.\n\nOpen brackets must be closed by the same type, in the correct order. Every close has a corresponding open.",
        examples=[
            {"input": 's = "()"', "output": "true"},
            {"input": 's = "()[]{}"', "output": "true"},
            {"input": 's = "(]"', "output": "false"},
        ],
        constraints=["1 <= s.length <= 10^4", "s consists of parentheses only ()[]{}."],
        followUp=None,
        editorial="Push opens. On close, the stack top must match. Stack empty at the end.",
        entry="isValid",
        paramNames=["s"],
        helpers=["json", "json"],
        py_params=[("s", "str")],
        py_ret="bool",
        js_params=[("s", "string")],
        js_ret="boolean",
        visible=[
            {"args": {"s": "()"}, "expected": True},
            {"args": {"s": "()[]{}"}, "expected": True},
            {"args": {"s": "(]"}, "expected": False},
        ],
        hidden=[
            {"args": {"s": "([)]"}, "expected": False},
            {"args": {"s": "{[]}"}, "expected": True},
            {"args": {"s": "]"}, "expected": False},
        ],
    )
    P(
        id="daily-temperatures",
        title="Daily Temperatures",
        difficulty="medium",
        tags=["Array", "Stack", "Monotonic Stack"],
        unitId="unit-03",
        kind="stretch",
        order=5,
        microsoftNote="Next greater element via a decreasing stack of indices.",
        statement="Given `temperatures` where `temperatures[i]` is the temperature on day `i`, return an array `answer` such that `answer[i]` is the number of days you have to wait after the `i`th day to get a warmer temperature. If there is no future day, `answer[i] == 0`.",
        examples=[{"input": "temperatures = [73,74,75,71,69,72,76,73]", "output": "[1,1,4,2,1,1,0,0]"}],
        constraints=["1 <= temperatures.length <= 10^5", "30 <= temperatures[i] <= 100"],
        followUp="O(n) time.",
        editorial="Monotonic decreasing stack of indices. When today's temp is warmer, pop and fill wait = i - idx.",
        entry="dailyTemperatures",
        paramNames=["temperatures"],
        helpers=["json", "json"],
        py_params=[("temperatures", "list[int]")],
        py_ret="list[int]",
        js_params=[("temperatures", "number[]")],
        js_ret="number[]",
        visible=[{"args": {"temperatures": [73, 74, 75, 71, 69, 72, 76, 73]}, "expected": [1, 1, 4, 2, 1, 1, 0, 0]}],
        hidden=[
            {"args": {"temperatures": [30, 40, 50, 60]}, "expected": [1, 1, 1, 0]},
            {"args": {"temperatures": [30, 60, 90]}, "expected": [1, 1, 0]},
        ],
    )


def write_unit4() -> None:
    P(
        id="binary-search",
        title="Binary Search",
        difficulty="easy",
        tags=["Array", "Binary Search"],
        unitId="unit-04",
        kind="core",
        order=1,
        microsoftNote="Write the loop bounds without an off-by-one. Say the invariant.",
        statement="Given a sorted array of integers `nums` (ascending, distinct) and an integer `target`, return the index of `target` or `-1` if it is not present. You must write an algorithm with O(log n) runtime.",
        examples=[{"input": "nums = [-1,0,3,5,9,12], target = 9", "output": "4"}],
        constraints=["1 <= nums.length <= 10^4", "-10^4 <= nums[i], target <= 10^4", "All integers in nums are unique.", "nums is sorted in ascending order."],
        followUp=None,
        editorial="lo, hi inclusive or exclusive — pick one and stick to it. Mid overflow: lo + (hi-lo)//2.",
        entry="search",
        paramNames=["nums", "target"],
        helpers=["json", "json", "json"],
        py_params=[("nums", "list[int]"), ("target", "int")],
        py_ret="int",
        js_params=[("nums", "number[]"), ("target", "number")],
        js_ret="number",
        visible=[
            {"args": {"nums": [-1, 0, 3, 5, 9, 12], "target": 9}, "expected": 4},
            {"args": {"nums": [-1, 0, 3, 5, 9, 12], "target": 2}, "expected": -1},
        ],
        hidden=[
            {"args": {"nums": [5], "target": 5}, "expected": 0},
            {"args": {"nums": [5], "target": -5}, "expected": -1},
        ],
    )
    P(
        id="search-rotated-sorted",
        title="Search in Rotated Sorted Array",
        difficulty="medium",
        tags=["Array", "Binary Search"],
        unitId="unit-04",
        kind="core",
        order=2,
        microsoftNote="Very common Microsoft medium. Decide which half is sorted, then whether target lives there.",
        statement="`nums` is a possibly rotated sorted array of **distinct** integers. Return the index of `target`, or `-1`. O(log n).",
        examples=[{"input": "nums = [4,5,6,7,0,1,2], target = 0", "output": "4"}],
        constraints=["1 <= nums.length <= 5000", "-10^4 <= nums[i] <= 10^4", "All values unique.", "-10^4 <= target <= 10^4"],
        followUp="What if duplicates are allowed?",
        editorial="If nums[lo] <= nums[mid], left half is sorted. Else right half is. Probe whether target is inside that sorted half.",
        entry="search",
        paramNames=["nums", "target"],
        helpers=["json", "json", "json"],
        py_params=[("nums", "list[int]"), ("target", "int")],
        py_ret="int",
        js_params=[("nums", "number[]"), ("target", "number")],
        js_ret="number",
        visible=[
            {"args": {"nums": [4, 5, 6, 7, 0, 1, 2], "target": 0}, "expected": 4},
            {"args": {"nums": [4, 5, 6, 7, 0, 1, 2], "target": 3}, "expected": -1},
        ],
        hidden=[
            {"args": {"nums": [1], "target": 0}, "expected": -1},
            {"args": {"nums": [3, 1], "target": 1}, "expected": 1},
            {"args": {"nums": [5, 1, 3], "target": 5}, "expected": 0},
        ],
    )
    P(
        id="find-peak-element",
        title="Find Peak Element",
        difficulty="medium",
        tags=["Array", "Binary Search"],
        unitId="unit-04",
        kind="core",
        order=3,
        microsoftNote="Binary search on slope. nums[-1] and nums[n] are -inf.",
        statement="A peak is an element strictly greater than its neighbors. Given `nums`, return **any** peak index. `nums[-1]` and `nums[n]` are considered `-∞`. O(log n).",
        examples=[{"input": "nums = [1,2,3,1]", "output": "2"}],
        constraints=["1 <= nums.length <= 1000", "-2^31 <= nums[i] <= 2^31 - 1", "nums[i] != nums[i + 1] for all valid i."],
        followUp=None,
        editorial="If nums[mid] < nums[mid+1], a peak exists on the right. Else on the left (including mid).",
        entry="findPeakElement",
        paramNames=["nums"],
        helpers=["json", "json"],
        py_params=[("nums", "list[int]")],
        py_ret="int",
        js_params=[("nums", "number[]")],
        js_ret="number",
        visible=[
            {"args": {"nums": [1, 2, 3, 1]}, "expected": 2},
        ],
        hidden=[
            {"args": {"nums": [1]}, "expected": 0},
            {"args": {"nums": [2, 1]}, "expected": 0},
        ],
    )
    # find peak second example may have peak at 1 or 5 - index 5 is 6 which is a peak, index 1 is 2 which is also a peak. Hidden tests use unique peaks where possible.
    P(
        id="first-bad-version",
        title="First Bad Version",
        difficulty="easy",
        tags=["Binary Search", "Interactive"],
        unitId="unit-04",
        kind="core",
        order=4,
        microsoftNote="API-style binary search. Minimize calls to isBadVersion.",
        statement="You are a product manager. Versions `[1, n]` go bad and stay bad. `isBadVersion(version)` is provided.\n\nImplement `firstBadVersion(n)` to find the first bad version. Minimize API calls.",
        examples=[{"input": "n = 5, bad = 4", "output": "4"}],
        constraints=["1 <= bad <= n <= 2^31 - 1"],
        followUp="How many API calls in the worst case?",
        editorial="Binary search for the first true. Classic lower-bound.",
        entry="firstBadVersion",
        paramNames=["n"],
        helpers=["json", "json", "first_bad_version"],
        py_params=[("n", "int")],
        py_ret="int",
        js_params=[("n", "number")],
        js_ret="number",
        visible=[
            {"args": {"n": 5}, "extra": {"bad": 4}, "expected": 4},
            {"args": {"n": 1}, "extra": {"bad": 1}, "expected": 1},
        ],
        hidden=[
            {"args": {"n": 10}, "extra": {"bad": 10}, "expected": 10},
            {"args": {"n": 10}, "extra": {"bad": 1}, "expected": 1},
        ],
    )
    P(
        id="koko-eating-bananas",
        title="Koko Eating Bananas",
        difficulty="medium",
        tags=["Array", "Binary Search"],
        unitId="unit-04",
        kind="stretch",
        order=5,
        microsoftNote="Binary search on the answer (speed k).",
        statement="Koko has `piles[i]` bananas in pile i. Guards return in `h` hours. She eats at speed `k` bananas/hour, one pile at a time, rounding hours **up**.\n\nReturn the minimum integer `k` such that she finishes in `h` hours.",
        examples=[{"input": "piles = [3,6,7,11], h = 8", "output": "4"}],
        constraints=["1 <= piles.length <= 10^4", "piles.length <= h <= 10^9", "1 <= piles[i] <= 10^9"],
        followUp=None,
        editorial="k in [1, max(piles)]. Feasible if sum(ceil(p/k)) <= h. Binary search the min feasible k.",
        entry="minEatingSpeed",
        paramNames=["piles", "h"],
        helpers=["json", "json", "json"],
        py_params=[("piles", "list[int]"), ("h", "int")],
        py_ret="int",
        js_params=[("piles", "number[]"), ("h", "number")],
        js_ret="number",
        visible=[
            {"args": {"piles": [3, 6, 7, 11], "h": 8}, "expected": 4},
            {"args": {"piles": [30, 11, 23, 4, 20], "h": 5}, "expected": 30},
        ],
        hidden=[
            {"args": {"piles": [30, 11, 23, 4, 20], "h": 6}, "expected": 23},
            {"args": {"piles": [1], "h": 1}, "expected": 1},
        ],
    )


def write_unit5() -> None:
    trees = [
        ("max-depth-binary-tree", "Maximum Depth of Binary Tree", "easy", 1, "core",
         "maxDepth", "Return the number of nodes along the longest path from the root down to the farthest leaf.",
         "DFS: 1 + max(left, right). BFS level count also works.",
         ["root"], ["json", "tree"],
         [{"args": {"root": [3, 9, 20, None, None, 15, 7]}, "expected": 3}, {"args": {"root": [1, None, 2]}, "expected": 2}],
         [{"args": {"root": []}, "expected": 0}, {"args": {"root": [1]}, "expected": 1}]),
        ("invert-binary-tree", "Invert Binary Tree", "easy", 2, "core",
         "invertTree", "Invert a binary tree (mirror it) and return its root.",
         "Swap children, recurse. Or BFS swap.",
         ["root"], ["tree", "tree"],
         [{"args": {"root": [4, 2, 7, 1, 3, 6, 9]}, "expected": [4, 7, 2, 9, 6, 3, 1]}],
         [{"args": {"root": [2, 1, 3]}, "expected": [2, 3, 1]}, {"args": {"root": []}, "expected": []}]),
        ("same-tree", "Same Tree", "easy", 3, "core",
         "isSameTree", "Given the roots of two binary trees `p` and `q`, write a function to check if they are the same (identical structure and values).",
         "Compare vals, then both lefts and both rights. Null mismatches fail.",
         ["p", "q"], ["json", "tree", "tree"],
         [{"args": {"p": [1, 2, 3], "q": [1, 2, 3]}, "expected": True}, {"args": {"p": [1, 2], "q": [1, None, 2]}, "expected": False}],
         [{"args": {"p": [], "q": []}, "expected": True}, {"args": {"p": [1, 2, 1], "q": [1, 1, 2]}, "expected": False}]),
        ("diameter-binary-tree", "Diameter of Binary Tree", "easy", 4, "core",
         "diameterOfBinaryTree", "The diameter is the length of the longest path between any two nodes, measured in **edges**. It may or may not pass through the root.",
         "For each node, diameter candidate = leftHeight + rightHeight. Recurse heights. Keep a global max.",
         ["root"], ["json", "tree"],
         [{"args": {"root": [1, 2, 3, 4, 5]}, "expected": 3}],
         [{"args": {"root": [1, 2]}, "expected": 1}, {"args": {"root": [1]}, "expected": 0}]),
        ("path-sum", "Path Sum", "easy", 5, "core",
         "hasPathSum", "Return true if the tree has a **root-to-leaf** path such that the sum of node values equals `targetSum`.",
         "DFS remaining sum. Leaf check: no children and remaining == node.val.",
         ["root", "targetSum"], ["json", "tree", "json"],
         [{"args": {"root": [5, 4, 8, 11, None, 13, 4, 7, 2, None, None, None, 1], "targetSum": 22}, "expected": True}],
         [{"args": {"root": [1, 2, 3], "targetSum": 5}, "expected": False}, {"args": {"root": [], "targetSum": 0}, "expected": False}]),
        ("level-order", "Binary Tree Level Order Traversal", "medium", 6, "core",
         "levelOrder", "Return the level-order traversal of node values (from left to right, level by level).",
         "Queue BFS. Record size at the start of each level.",
         ["root"], ["json", "tree"],
         [{"args": {"root": [3, 9, 20, None, None, 15, 7]}, "expected": [[3], [9, 20], [15, 7]]}],
         [{"args": {"root": [1]}, "expected": [[1]]}, {"args": {"root": []}, "expected": []}]),
        ("symmetric-tree", "Symmetric Tree", "easy", 7, "core",
         "isSymmetric", "Return true if the binary tree is a mirror of itself (symmetric around its center).",
         "Helper(a,b): both null, or vals equal and helper(a.left,b.right) and helper(a.right,b.left).",
         ["root"], ["json", "tree"],
         [{"args": {"root": [1, 2, 2, 3, 4, 4, 3]}, "expected": True}, {"args": {"root": [1, 2, 2, None, 3, None, 3]}, "expected": False}],
         [{"args": {"root": [1]}, "expected": True}]),
    ]
    py_types = {
        "maxDepth": ([("root", "Optional[TreeNode]")], "int"),
        "invertTree": ([("root", "Optional[TreeNode]")], "Optional[TreeNode]"),
        "isSameTree": ([("p", "Optional[TreeNode]"), ("q", "Optional[TreeNode]")], "bool"),
        "diameterOfBinaryTree": ([("root", "Optional[TreeNode]")], "int"),
        "hasPathSum": ([("root", "Optional[TreeNode]"), ("targetSum", "int")], "bool"),
        "levelOrder": ([("root", "Optional[TreeNode]")], "list[list[int]]"),
        "isSymmetric": ([("root", "Optional[TreeNode]")], "bool"),
    }
    js_types = {
        "maxDepth": ([("root", "TreeNode|null")], "number"),
        "invertTree": ([("root", "TreeNode|null")], "TreeNode|null"),
        "isSameTree": ([("p", "TreeNode|null"), ("q", "TreeNode|null")], "boolean"),
        "diameterOfBinaryTree": ([("root", "TreeNode|null")], "number"),
        "hasPathSum": ([("root", "TreeNode|null"), ("targetSum", "number")], "boolean"),
        "levelOrder": ([("root", "TreeNode|null")], "number[][]"),
        "isSymmetric": ([("root", "TreeNode|null")], "boolean"),
    }
    notes = {
        "max-depth-binary-tree": "Tree height is muscle memory for Microsoft.",
        "invert-binary-tree": "The joke question that still shows up as a warmup.",
        "same-tree": "Null handling. Don't crash on empty trees.",
        "diameter-binary-tree": "Height vs diameter — the return value to the parent is height, the answer is a side effect.",
        "path-sum": "Root-to-leaf, not any path. Microsoft asks path variants constantly.",
        "level-order": "Iterative BFS. They like seeing a queue, not only recursion.",
        "symmetric-tree": "Mirror comparison, not 'is BST'.",
    }
    for pid, title, diff, order, kind, entry, stmt, ed, params, helpers, vis, hid in trees:
        pp, pr = py_types[entry]
        jp, jr = js_types[entry]
        P(
            id=pid, title=title, difficulty=diff, tags=["Tree", "DFS", "BFS"],
            unitId="unit-05", kind=kind, order=order, microsoftNote=notes[pid],
            statement=stmt + "\n\nTrees are given as level-order arrays (`null` for missing children).",
            examples=[{"input": json.dumps(vis[0]["args"]), "output": json.dumps(vis[0]["expected"])}],
            constraints=["The number of nodes is in [0, 10^4].", "-1000 <= Node.val <= 1000"],
            followUp=None, editorial=ed, entry=entry, paramNames=params, helpers=helpers,
            py_params=pp, py_ret=pr, js_params=jp, js_ret=jr, visible=vis, hidden=hid,
        )


def write_unit6() -> None:
    P(
        id="validate-bst",
        title="Validate Binary Search Tree",
        difficulty="medium",
        tags=["Tree", "BST", "DFS"],
        unitId="unit-06",
        kind="core",
        order=1,
        microsoftNote="Bounds, not just left < root < right on one node. A classic fail.",
        statement="Given the root of a binary tree, determine if it is a valid **binary search tree**.\n\nA valid BST: the left subtree contains only keys **strictly less** than the node, the right only **strictly greater**, and both subtrees are BSTs.",
        examples=[{"input": "root = [2,1,3]", "output": "true"}, {"input": "root = [5,1,4,null,null,3,6]", "output": "false"}],
        constraints=["The number of nodes is in [1, 10^4].", "-2^31 <= Node.val <= 2^31 - 1"],
        followUp="Inorder should be strictly increasing — that is another solution.",
        editorial="DFS with (low, high) bounds. Left child gets high=root.val, right gets low=root.val. Strict inequalities.",
        entry="isValidBST",
        paramNames=["root"],
        helpers=["json", "tree"],
        py_params=[("root", "Optional[TreeNode]")],
        py_ret="bool",
        js_params=[("root", "TreeNode|null")],
        js_ret="boolean",
        visible=[
            {"args": {"root": [2, 1, 3]}, "expected": True},
            {"args": {"root": [5, 1, 4, None, None, 3, 6]}, "expected": False},
        ],
        hidden=[
            {"args": {"root": [5, 4, 6, None, None, 3, 7]}, "expected": False},
            {"args": {"root": [1]}, "expected": True},
        ],
    )
    P(
        id="lca-bst",
        title="Lowest Common Ancestor of a BST",
        difficulty="medium",
        tags=["Tree", "BST"],
        unitId="unit-06",
        kind="core",
        order=2,
        microsoftNote="Walk down from the root; split point is the LCA. p and q are values.",
        statement="Given a BST `root` and two node values `p` and `q` that exist in the tree, return the value of their lowest common ancestor.\n\nThe LCA is the lowest node that has both `p` and `q` as descendants (a node can be a descendant of itself).",
        examples=[{"input": "root = [6,2,8,0,4,7,9,null,null,3,5], p = 2, q = 8", "output": "6"}],
        constraints=["The number of nodes is in [2, 10^5].", "-10^9 <= Node.val <= 10^9", "All values unique.", "p != q", "p and q exist in the tree."],
        followUp="Iterative, O(1) extra space.",
        editorial="If both p and q are < root, go left. Both > root, go right. Else root is the split.",
        entry="lowestCommonAncestor",
        paramNames=["root", "p", "q"],
        helpers=["json", "tree", "json", "json"],
        py_params=[("root", "Optional[TreeNode]"), ("p", "int"), ("q", "int")],
        py_ret="int",
        js_params=[("root", "TreeNode|null"), ("p", "number"), ("q", "number")],
        js_ret="number",
        visible=[
            {"args": {"root": [6, 2, 8, 0, 4, 7, 9, None, None, 3, 5], "p": 2, "q": 8}, "expected": 6},
            {"args": {"root": [6, 2, 8, 0, 4, 7, 9, None, None, 3, 5], "p": 2, "q": 4}, "expected": 2},
        ],
        hidden=[{"args": {"root": [2, 1], "p": 2, "q": 1}, "expected": 2}],
    )
    P(
        id="right-side-view",
        title="Binary Tree Right Side View",
        difficulty="medium",
        tags=["Tree", "BFS"],
        unitId="unit-06",
        kind="core",
        order=3,
        microsoftNote="Level-order; last node on each level.",
        statement="Given the root of a binary tree, imagine yourself standing on the **right side** of it. Return the values of the nodes you can see ordered from top to bottom.",
        examples=[{"input": "root = [1,2,3,null,5,null,4]", "output": "[1,3,4]"}],
        constraints=["The number of nodes is in [0, 100].", "-100 <= Node.val <= 100"],
        followUp="DFS visiting right first also works.",
        editorial="BFS. Append the last node of each level. Or DFS right-first, record the first visit at each depth.",
        entry="rightSideView",
        paramNames=["root"],
        helpers=["json", "tree"],
        py_params=[("root", "Optional[TreeNode]")],
        py_ret="list[int]",
        js_params=[("root", "TreeNode|null")],
        js_ret="number[]",
        visible=[{"args": {"root": [1, 2, 3, None, 5, None, 4]}, "expected": [1, 3, 4]}],
        hidden=[{"args": {"root": [1, None, 3]}, "expected": [1, 3]}, {"args": {"root": []}, "expected": []}],
    )
    P(
        id="construct-preorder-inorder",
        title="Construct Binary Tree from Preorder and Inorder Traversal",
        difficulty="medium",
        tags=["Tree", "Divide and Conquer"],
        unitId="unit-06",
        kind="core",
        order=4,
        microsoftNote="Onsite favorite. Preorder gives the root; inorder splits left/right.",
        statement="Given two integer arrays `preorder` and `inorder` where `preorder` is the preorder traversal of a binary tree and `inorder` is the inorder traversal of the same tree (distinct values), construct and return the binary tree.",
        examples=[{"input": "preorder = [3,9,20,15,7], inorder = [9,3,15,20,7]", "output": "[3,9,20,null,null,15,7]"}],
        constraints=["1 <= preorder.length <= 3000", "inorder.length == preorder.length", "All values unique.", "inorder is the inorder of the tree, preorder is the preorder of the tree."],
        followUp="O(n) with an index map for inorder.",
        editorial="Root = preorder[0]. Find it in inorder. Left size = index. Recurse on slices. Map value→inorder index.",
        entry="buildTree",
        paramNames=["preorder", "inorder"],
        helpers=["tree", "json", "json"],
        py_params=[("preorder", "list[int]"), ("inorder", "list[int]")],
        py_ret="Optional[TreeNode]",
        js_params=[("preorder", "number[]"), ("inorder", "number[]")],
        js_ret="TreeNode|null",
        visible=[{"args": {"preorder": [3, 9, 20, 15, 7], "inorder": [9, 3, 15, 20, 7]}, "expected": [3, 9, 20, None, None, 15, 7]}],
        hidden=[{"args": {"preorder": [-1], "inorder": [-1]}, "expected": [-1]}],
    )
    P(
        id="zigzag-level-order",
        title="Binary Tree Zigzag Level Order Traversal",
        difficulty="medium",
        tags=["Tree", "BFS"],
        unitId="unit-06",
        kind="core",
        order=5,
        microsoftNote="Level order with alternating reverse. Frequently reported at Microsoft.",
        statement="Given the root of a binary tree, return the zigzag level order traversal of its nodes' values (i.e., from left to right, then right to left for the next level and alternate).",
        examples=[{"input": "root = [3,9,20,null,null,15,7]", "output": "[[3],[20,9],[15,7]]"}],
        constraints=["The number of nodes is in [0, 2000].", "-100 <= Node.val <= 100"],
        followUp=None,
        editorial="BFS. Reverse every odd level (0-index even is L→R).",
        entry="zigzagLevelOrder",
        paramNames=["root"],
        helpers=["json", "tree"],
        py_params=[("root", "Optional[TreeNode]")],
        py_ret="list[list[int]]",
        js_params=[("root", "TreeNode|null")],
        js_ret="number[][]",
        visible=[{"args": {"root": [3, 9, 20, None, None, 15, 7]}, "expected": [[3], [20, 9], [15, 7]]}],
        hidden=[{"args": {"root": [1]}, "expected": [[1]]}, {"args": {"root": []}, "expected": []}],
    )
    P(
        id="max-path-sum",
        title="Binary Tree Maximum Path Sum",
        difficulty="hard",
        tags=["Tree", "DFS", "DP"],
        unitId="unit-06",
        kind="stretch",
        order=6,
        microsoftNote="The Hard tree they actually ask. Gain returned to parent vs path through node.",
        statement="A **path** is a sequence of nodes where each pair of adjacent nodes has an edge. A node appears at most once. The path does **not** need to pass through the root.\n\nThe **path sum** is the sum of the node values. Return the maximum path sum of any non-empty path.",
        examples=[{"input": "root = [1,2,3]", "output": "6"}, {"input": "root = [-10,9,20,null,null,15,7]", "output": "42"}],
        constraints=["The number of nodes is in [1, 3 * 10^4].", "-1000 <= Node.val <= 1000"],
        followUp=None,
        editorial="For each node, gain to parent = node.val + max(0, leftGain, rightGain). Best path through node = node.val + max(0,left) + max(0,right). Track global max.",
        entry="maxPathSum",
        paramNames=["root"],
        helpers=["json", "tree"],
        py_params=[("root", "Optional[TreeNode]")],
        py_ret="int",
        js_params=[("root", "TreeNode|null")],
        js_ret="number",
        visible=[
            {"args": {"root": [1, 2, 3]}, "expected": 6},
            {"args": {"root": [-10, 9, 20, None, None, 15, 7]}, "expected": 42},
        ],
        hidden=[{"args": {"root": [-3]}, "expected": -3}],
    )


def write_unit7() -> None:
    P(
        id="number-of-islands",
        title="Number of Islands",
        difficulty="medium",
        tags=["Graph", "DFS", "BFS", "Matrix"],
        unitId="unit-07",
        kind="core",
        order=1,
        microsoftNote="Grid DFS/BFS. Cloud-infra teams ask this constantly.",
        statement="Given an `m x n` 2D binary grid `grid` which represents a map of `'1'`s (land) and `'0'`s (water), return the number of islands.\n\nAn island is surrounded by water and is formed by connecting adjacent lands **horizontally or vertically**.",
        examples=[{"input": 'grid = [["1","1","0"],["1","1","0"],["0","0","1"]]', "output": "2"}],
        constraints=["m == grid.length", "n == grid[i].length", "1 <= m, n <= 300", "grid[i][j] is '0' or '1'."],
        followUp=None,
        editorial="Scan. On a '1', increment and DFS/BFS flood to '0' or a visited mark.",
        entry="numIslands",
        paramNames=["grid"],
        helpers=["json", "json"],
        py_params=[("grid", "list[list[str]]")],
        py_ret="int",
        js_params=[("grid", "character[][]")],
        js_ret="number",
        visible=[{
            "args": {"grid": [["1", "1", "1", "1", "0"], ["1", "1", "0", "1", "0"], ["1", "1", "0", "0", "0"], ["0", "0", "0", "0", "0"]]},
            "expected": 1,
        }],
        hidden=[
            {"args": {"grid": [["1", "1", "0", "0", "0"], ["1", "1", "0", "0", "0"], ["0", "0", "1", "0", "0"], ["0", "0", "0", "1", "1"]]}, "expected": 3},
            {"args": {"grid": [["0"]]}, "expected": 0},
        ],
    )
    P(
        id="rotting-oranges",
        title="Rotting Oranges",
        difficulty="medium",
        tags=["Graph", "BFS", "Matrix"],
        unitId="unit-07",
        kind="core",
        order=2,
        microsoftNote="Multi-source BFS. Minutes = max distance from any rotten orange.",
        statement="In a grid, `0` is empty, `1` is a fresh orange, `2` is rotten. Every minute, any fresh orange 4-directionally adjacent to a rotten one becomes rotten.\n\nReturn the minimum minutes until no fresh orange remains. If impossible, return `-1`.",
        examples=[{"input": "grid = [[2,1,1],[1,1,0],[0,1,1]]", "output": "4"}],
        constraints=["m == grid.length", "n == grid[i].length", "1 <= m, n <= 10", "grid[i][j] is 0, 1, or 2."],
        followUp=None,
        editorial="Queue all rotten at minute 0. BFS. Count fresh; if leftover fresh at the end, -1.",
        entry="orangesRotting",
        paramNames=["grid"],
        helpers=["json", "json"],
        py_params=[("grid", "list[list[int]]")],
        py_ret="int",
        js_params=[("grid", "number[][]")],
        js_ret="number",
        visible=[
            {"args": {"grid": [[2, 1, 1], [1, 1, 0], [0, 1, 1]]}, "expected": 4},
            {"args": {"grid": [[2, 1, 1], [0, 1, 1], [1, 0, 1]]}, "expected": -1},
        ],
        hidden=[{"args": {"grid": [[0, 2]]}, "expected": 0}],
    )
    P(
        id="clone-graph",
        title="Clone Graph",
        difficulty="medium",
        tags=["Graph", "DFS", "Hash Map"],
        unitId="unit-07",
        kind="core",
        order=3,
        microsoftNote="Map old node → new node while DFS/BFS. Don't recurse infinitely.",
        statement="Given a reference of a node in a **connected** undirected graph, return a deep copy of the graph.\n\nEach node has a val and a list of neighbors. The input is an adjacency list. Node vals are 1-indexed as in the list order.",
        examples=[{"input": "adjList = [[2,4],[1,3],[2,4],[1,3]]", "output": "[[2,4],[1,3],[2,4],[1,3]]"}],
        constraints=["The number of nodes is in [0, 100].", "1 <= Node.val <= 100", "Node.val is unique.", "The graph is connected."],
        followUp=None,
        editorial="HashMap original→clone. DFS: create clone, then attach cloned neighbors.",
        entry="cloneGraph",
        paramNames=["node"],
        helpers=["graph", "graph"],
        py_params=[("node", "Optional[Node]")],
        py_ret="Optional[Node]",
        js_params=[("node", "Node|null")],
        js_ret="Node|null",
        visible=[{"args": {"node": [[2, 4], [1, 3], [2, 4], [1, 3]]}, "expected": [[2, 4], [1, 3], [2, 4], [1, 3]]}],
        hidden=[{"args": {"node": [[]]}, "expected": [[]]}, {"args": {"node": []}, "expected": []}],
    )
    P(
        id="course-schedule",
        title="Course Schedule",
        difficulty="medium",
        tags=["Graph", "Topological Sort"],
        unitId="unit-07",
        kind="core",
        order=4,
        microsoftNote="Cycle detection. Kahn or DFS colors.",
        statement="There are `numCourses` labeled `0` to `numCourses - 1`. `prerequisites[i] = [ai, bi]` means you must take `bi` before `ai`.\n\nReturn `true` if you can finish all courses (the graph is a DAG).",
        examples=[{"input": "numCourses = 2, prerequisites = [[1,0]]", "output": "true"}],
        constraints=["1 <= numCourses <= 2000", "0 <= prerequisites.length <= 5000", "prerequisites[i].length == 2", "0 <= ai, bi < numCourses"],
        followUp="Return a valid order (Course Schedule II).",
        editorial="Build adj + indegree. Queue zero-indegree. If you process all nodes, no cycle.",
        entry="canFinish",
        paramNames=["numCourses", "prerequisites"],
        helpers=["json", "json", "json"],
        py_params=[("numCourses", "int"), ("prerequisites", "list[list[int]]")],
        py_ret="bool",
        js_params=[("numCourses", "number"), ("prerequisites", "number[][]")],
        js_ret="boolean",
        visible=[
            {"args": {"numCourses": 2, "prerequisites": [[1, 0]]}, "expected": True},
            {"args": {"numCourses": 2, "prerequisites": [[1, 0], [0, 1]]}, "expected": False},
        ],
        hidden=[
            {"args": {"numCourses": 1, "prerequisites": []}, "expected": True},
            {"args": {"numCourses": 3, "prerequisites": [[1, 0], [2, 1]]}, "expected": True},
        ],
    )
    P(
        id="zero-one-matrix",
        title="01 Matrix",
        difficulty="medium",
        tags=["Graph", "BFS", "Matrix"],
        unitId="unit-07",
        kind="core",
        order=5,
        microsoftNote="Multi-source BFS from every 0.",
        statement="Given an `m x n` binary matrix `mat`, return the distance of the nearest `0` for each cell. Adjacent cells are 4-directional, distance 1 each.",
        examples=[{"input": "mat = [[0,0,0],[0,1,0],[1,1,1]]", "output": "[[0,0,0],[0,1,0],[1,2,1]]"}],
        constraints=["m == mat.length", "n == mat[i].length", "1 <= m, n <= 200", "mat[i][j] is 0 or 1.", "There is at least one 0."],
        followUp="DP two-pass is an alternative to BFS.",
        editorial="Queue all zeros. BFS outward, filling unseen 1s with dist.",
        entry="updateMatrix",
        paramNames=["mat"],
        helpers=["json", "json"],
        py_params=[("mat", "list[list[int]]")],
        py_ret="list[list[int]]",
        js_params=[("mat", "number[][]")],
        js_ret="number[][]",
        visible=[{"args": {"mat": [[0, 0, 0], [0, 1, 0], [1, 1, 1]]}, "expected": [[0, 0, 0], [0, 1, 0], [1, 2, 1]]}],
        hidden=[{"args": {"mat": [[0, 1], [1, 1]]}, "expected": [[0, 1], [1, 2]]}],
    )
    P(
        id="word-search",
        title="Word Search",
        difficulty="medium",
        tags=["Matrix", "Backtracking"],
        unitId="unit-07",
        kind="stretch",
        order=6,
        microsoftNote="Backtracking on a grid. Mark visited, unmark on return.",
        statement="Given an `m x n` grid of characters `board` and a string `word`, return `true` if `word` exists in the grid. The word can be constructed from sequentially adjacent cells (4-dir). The same cell may not be used twice.",
        examples=[{"input": 'board = [["A","B","C","E"],["S","F","C","S"],["A","D","E","E"]], word = "ABCCED"', "output": "true"}],
        constraints=["1 <= m, n <= 6", "1 <= word.length <= 15", "board and word consist of uppercase and lowercase English letters."],
        followUp=None,
        editorial="Start DFS from each cell. Mutate board to mark visited, restore after.",
        entry="exist",
        paramNames=["board", "word"],
        helpers=["json", "json", "json"],
        py_params=[("board", "list[list[str]]"), ("word", "str")],
        py_ret="bool",
        js_params=[("board", "character[][]"), ("word", "string")],
        js_ret="boolean",
        visible=[{
            "args": {"board": [["A", "B", "C", "E"], ["S", "F", "C", "S"], ["A", "D", "E", "E"]], "word": "ABCCED"},
            "expected": True,
        }],
        hidden=[
            {"args": {"board": [["A", "B", "C", "E"], ["S", "F", "C", "S"], ["A", "D", "E", "E"]], "word": "SEE"}, "expected": True},
            {"args": {"board": [["A", "B", "C", "E"], ["S", "F", "C", "S"], ["A", "D", "E", "E"]], "word": "ABCB"}, "expected": False},
        ],
    )


def write_unit8() -> None:
    P(
        id="top-k-frequent",
        title="Top K Frequent Elements",
        difficulty="medium",
        tags=["Heap", "Hash Map"],
        unitId="unit-08",
        kind="core",
        order=1,
        microsoftNote="Heap or bucket sort. Return any order.",
        statement="Given an integer array `nums` and an integer `k`, return the `k` most frequent elements. You may return the answer in any order.",
        examples=[{"input": "nums = [1,1,1,2,2,3], k = 2", "output": "[1,2]"}],
        constraints=["1 <= nums.length <= 10^5", "k is in the range [1, the number of unique elements in nums].", "It is guaranteed that the answer is unique."],
        followUp="Better than n log n.",
        editorial="Count frequencies. Heap of size k, or bucket sort by frequency.",
        entry="topKFrequent",
        paramNames=["nums", "k"],
        helpers=["json", "json", "json"],
        py_params=[("nums", "list[int]"), ("k", "int")],
        py_ret="list[int]",
        js_params=[("nums", "number[]"), ("k", "number")],
        js_ret="number[]",
        visible=[{"args": {"nums": [1, 1, 1, 2, 2, 3], "k": 2}, "expected": [1, 2], "compare": "sorted"}],
        hidden=[{"args": {"nums": [1], "k": 1}, "expected": [1], "compare": "sorted"}],
    )
    P(
        id="kth-largest",
        title="Kth Largest Element in an Array",
        difficulty="medium",
        tags=["Heap", "Quickselect"],
        unitId="unit-08",
        kind="core",
        order=2,
        microsoftNote="Heap of size k or quickselect. Sorting is acceptable if you name the complexity.",
        statement="Given an integer array `nums` and an integer `k`, return the `k`th **largest** element in the array (1-indexed: 1 = largest).",
        examples=[{"input": "nums = [3,2,1,5,6,4], k = 2", "output": "5"}],
        constraints=["1 <= k <= nums.length <= 10^5", "-10^4 <= nums[i] <= 10^4"],
        followUp="Quickselect expected O(n).",
        editorial="Min-heap of size k. Or sort reverse and index k-1.",
        entry="findKthLargest",
        paramNames=["nums", "k"],
        helpers=["json", "json", "json"],
        py_params=[("nums", "list[int]"), ("k", "int")],
        py_ret="int",
        js_params=[("nums", "number[]"), ("k", "number")],
        js_ret="number",
        visible=[
            {"args": {"nums": [3, 2, 1, 5, 6, 4], "k": 2}, "expected": 5},
            {"args": {"nums": [3, 2, 3, 1, 2, 4, 5, 5, 6], "k": 4}, "expected": 4},
        ],
        hidden=[{"args": {"nums": [1], "k": 1}, "expected": 1}],
    )
    P(
        id="merge-intervals",
        title="Merge Intervals",
        difficulty="medium",
        tags=["Array", "Intervals", "Sorting"],
        unitId="unit-08",
        kind="core",
        order=3,
        microsoftNote="Sort by start, then scan and merge when current.start <= last.end.",
        statement="Given an array of `intervals` where `intervals[i] = [starti, endi]`, merge all overlapping intervals and return an array of the non-overlapping intervals that cover all the intervals in the input.",
        examples=[{"input": "intervals = [[1,3],[2,6],[8,10],[15,18]]", "output": "[[1,6],[8,10],[15,18]]"}],
        constraints=["1 <= intervals.length <= 10^4", "intervals[i].length == 2", "0 <= starti <= endi <= 10^4"],
        followUp=None,
        editorial="Sort by start. If next.start <= cur.end, cur.end = max. Else push cur and move.",
        entry="merge",
        paramNames=["intervals"],
        helpers=["json", "json"],
        py_params=[("intervals", "list[list[int]]")],
        py_ret="list[list[int]]",
        js_params=[("intervals", "number[][]")],
        js_ret="number[][]",
        visible=[{"args": {"intervals": [[1, 3], [2, 6], [8, 10], [15, 18]]}, "expected": [[1, 6], [8, 10], [15, 18]]}],
        hidden=[
            {"args": {"intervals": [[1, 4], [4, 5]]}, "expected": [[1, 5]]},
            {"args": {"intervals": [[1, 4], [0, 4]]}, "expected": [[0, 4]]},
        ],
    )
    P(
        id="non-overlapping-intervals",
        title="Non-overlapping Intervals",
        difficulty="medium",
        tags=["Array", "Greedy", "Intervals"],
        unitId="unit-08",
        kind="core",
        order=4,
        microsoftNote="Minimum removals = n - maximum non-overlapping. Sort by end.",
        statement="Given an array of intervals `intervals` where `intervals[i] = [starti, endi]`, return the minimum number of intervals you need to remove to make the rest non-overlapping.\n\nTwo intervals overlap if they share any points except if they only touch at an endpoint: `[1,2]` and `[2,3]` do **not** overlap.",
        examples=[{"input": "intervals = [[1,2],[2,3],[3,4],[1,3]]", "output": "1"}],
        constraints=["1 <= intervals.length <= 10^5", "intervals[i].length == 2", "-5 * 10^4 <= starti < endi <= 5 * 10^4"],
        followUp=None,
        editorial="Sort by end. Greedily keep an interval if start >= last_end. Removals = n - kept.",
        entry="eraseOverlapIntervals",
        paramNames=["intervals"],
        helpers=["json", "json"],
        py_params=[("intervals", "list[list[int]]")],
        py_ret="int",
        js_params=[("intervals", "number[][]")],
        js_ret="number",
        visible=[{"args": {"intervals": [[1, 2], [2, 3], [3, 4], [1, 3]]}, "expected": 1}],
        hidden=[
            {"args": {"intervals": [[1, 2], [1, 2], [1, 2]]}, "expected": 2},
            {"args": {"intervals": [[1, 2], [2, 3]]}, "expected": 0},
        ],
    )
    P(
        id="meeting-rooms-ii",
        title="Meeting Rooms II",
        difficulty="medium",
        tags=["Heap", "Intervals"],
        unitId="unit-08",
        kind="stretch",
        order=5,
        microsoftNote="Min rooms = max overlap. Sort starts; min-heap of end times.",
        statement="Given an array of meeting time intervals `intervals` where `intervals[i] = [starti, endi]`, return the minimum number of conference rooms required.",
        examples=[{"input": "intervals = [[0,30],[5,10],[15,20]]", "output": "2"}],
        constraints=["1 <= intervals.length <= 10^4", "0 <= starti < endi <= 10^6"],
        followUp=None,
        editorial="Sort by start. Heap of end times. If start >= heap.min, pop (reuse room). After each meeting, push its end. The answer is the maximum heap size, equivalently the heap size if you never shrink except on reuse.",
        entry="minMeetingRooms",
        paramNames=["intervals"],
        helpers=["json", "json"],
        py_params=[("intervals", "list[list[int]]")],
        py_ret="int",
        js_params=[("intervals", "number[][]")],
        js_ret="number",
        visible=[
            {"args": {"intervals": [[0, 30], [5, 10], [15, 20]]}, "expected": 2},
            {"args": {"intervals": [[7, 10], [2, 4]]}, "expected": 1},
        ],
        hidden=[{"args": {"intervals": [[1, 5], [8, 9], [8, 9]]}, "expected": 2}],
    )


def write_unit9() -> None:
    P(
        id="climbing-stairs",
        title="Climbing Stairs",
        difficulty="easy",
        tags=["DP"],
        unitId="unit-09",
        kind="core",
        order=1,
        microsoftNote="Fibonacci DP. Name the recurrence.",
        statement="You are climbing a staircase. It takes `n` steps to reach the top. Each time you can climb `1` or `2` steps. In how many distinct ways can you climb to the top?",
        examples=[{"input": "n = 2", "output": "2"}, {"input": "n = 3", "output": "3"}],
        constraints=["1 <= n <= 45"],
        followUp="O(1) space.",
        editorial="dp[i] = dp[i-1] + dp[i-2]. Base 1, 2.",
        entry="climbStairs",
        paramNames=["n"],
        helpers=["json", "json"],
        py_params=[("n", "int")],
        py_ret="int",
        js_params=[("n", "number")],
        js_ret="number",
        visible=[{"args": {"n": 2}, "expected": 2}, {"args": {"n": 3}, "expected": 3}],
        hidden=[{"args": {"n": 1}, "expected": 1}, {"args": {"n": 5}, "expected": 8}],
    )
    P(
        id="house-robber",
        title="House Robber",
        difficulty="medium",
        tags=["DP", "Array"],
        unitId="unit-09",
        kind="core",
        order=2,
        microsoftNote="1D DP: rob this and skip previous, or skip this.",
        statement="You are a robber. `nums[i]` is the money in house i. Adjacent houses have a security system — you cannot rob two adjacent houses. Return the maximum amount you can rob.",
        examples=[{"input": "nums = [1,2,3,1]", "output": "4"}],
        constraints=["1 <= nums.length <= 100", "0 <= nums[i] <= 400"],
        followUp="Circular street is House Robber II.",
        editorial="dp[i] = max(dp[i-1], dp[i-2] + nums[i]). Two rolling vars.",
        entry="rob",
        paramNames=["nums"],
        helpers=["json", "json"],
        py_params=[("nums", "list[int]")],
        py_ret="int",
        js_params=[("nums", "number[]")],
        js_ret="number",
        visible=[{"args": {"nums": [1, 2, 3, 1]}, "expected": 4}, {"args": {"nums": [2, 7, 9, 3, 1]}, "expected": 12}],
        hidden=[{"args": {"nums": [2, 1, 1, 2]}, "expected": 4}],
    )
    P(
        id="coin-change",
        title="Coin Change",
        difficulty="medium",
        tags=["DP"],
        unitId="unit-09",
        kind="core",
        order=3,
        microsoftNote="Unbounded knapsack. Microsoft textbook DP.",
        statement="You are given coins of different denominations and a total amount of money `amount`. Return the fewest number of coins that you need to make up that amount. If it is impossible, return `-1`. You may use each coin as many times as you want.",
        examples=[{"input": "coins = [1,2,5], amount = 11", "output": "3"}],
        constraints=["1 <= coins.length <= 12", "1 <= coins[i] <= 2^31 - 1", "0 <= amount <= 10^4"],
        followUp="What is Coin Change II counting combinations?",
        editorial="dp[x] = min coins to make x. dp[0]=0, else inf. For each coin, update amounts upward.",
        entry="coinChange",
        paramNames=["coins", "amount"],
        helpers=["json", "json", "json"],
        py_params=[("coins", "list[int]"), ("amount", "int")],
        py_ret="int",
        js_params=[("coins", "number[]"), ("amount", "number")],
        js_ret="number",
        visible=[
            {"args": {"coins": [1, 2, 5], "amount": 11}, "expected": 3},
            {"args": {"coins": [2], "amount": 3}, "expected": -1},
        ],
        hidden=[{"args": {"coins": [1], "amount": 0}, "expected": 0}],
    )
    P(
        id="unique-paths",
        title="Unique Paths",
        difficulty="medium",
        tags=["DP", "Matrix"],
        unitId="unit-09",
        kind="core",
        order=4,
        microsoftNote="Grid DP. Combinatorics follow-up is C(m+n-2, m-1).",
        statement="A robot is on an `m x n` grid at top-left. It can only move down or right. How many unique paths to the bottom-right?",
        examples=[{"input": "m = 3, n = 7", "output": "28"}],
        constraints=["1 <= m, n <= 100", "The answer is at most 2 * 10^9."],
        followUp="O(min(m,n)) space.",
        editorial="dp[i][j] = dp[i-1][j] + dp[i][j-1]. First row/col = 1.",
        entry="uniquePaths",
        paramNames=["m", "n"],
        helpers=["json", "json", "json"],
        py_params=[("m", "int"), ("n", "int")],
        py_ret="int",
        js_params=[("m", "number"), ("n", "number")],
        js_ret="number",
        visible=[{"args": {"m": 3, "n": 7}, "expected": 28}, {"args": {"m": 3, "n": 2}, "expected": 3}],
        hidden=[{"args": {"m": 1, "n": 1}, "expected": 1}],
    )
    P(
        id="longest-increasing-subsequence",
        title="Longest Increasing Subsequence",
        difficulty="medium",
        tags=["DP", "Binary Search"],
        unitId="unit-09",
        kind="core",
        order=5,
        microsoftNote="O(n^2) DP is acceptable; mention patience sorting O(n log n).",
        statement="Given an integer array `nums`, return the length of the longest strictly increasing subsequence.",
        examples=[{"input": "nums = [10,9,2,5,3,7,101,18]", "output": "4"}],
        constraints=["1 <= nums.length <= 2500", "-10^4 <= nums[i] <= 10^4"],
        followUp="O(n log n).",
        editorial="dp[i] = 1 + max(dp[j] for j < i if nums[j] < nums[i]). Or tails binary search.",
        entry="lengthOfLIS",
        paramNames=["nums"],
        helpers=["json", "json"],
        py_params=[("nums", "list[int]")],
        py_ret="int",
        js_params=[("nums", "number[]")],
        js_ret="number",
        visible=[{"args": {"nums": [10, 9, 2, 5, 3, 7, 101, 18]}, "expected": 4}, {"args": {"nums": [0, 1, 0, 3, 2, 3]}, "expected": 4}],
        hidden=[{"args": {"nums": [7, 7, 7, 7]}, "expected": 1}],
    )
    P(
        id="word-break",
        title="Word Break",
        difficulty="medium",
        tags=["DP", "String", "Trie"],
        unitId="unit-09",
        kind="core",
        order=6,
        microsoftNote="dp[i] = whether s[:i] can be segmented.",
        statement="Given a string `s` and a dictionary `wordDict`, return `true` if `s` can be segmented into a space-separated sequence of one or more dictionary words. Words may be reused.",
        examples=[{"input": 's = "leetcode", wordDict = ["leet","code"]', "output": "true"}],
        constraints=["1 <= s.length <= 300", "1 <= wordDict.length <= 1000", "1 <= wordDict[i].length <= 20", "s and words consist of lowercase letters.", "All dictionary words unique."],
        followUp=None,
        editorial="dp[0]=True. For i in 1..n, if some word ends at i and dp[i-len] and s[i-len:i]==word.",
        entry="wordBreak",
        paramNames=["s", "wordDict"],
        helpers=["json", "json", "json"],
        py_params=[("s", "str"), ("wordDict", "list[str]")],
        py_ret="bool",
        js_params=[("s", "string"), ("wordDict", "string[]")],
        js_ret="boolean",
        visible=[
            {"args": {"s": "leetcode", "wordDict": ["leet", "code"]}, "expected": True},
            {"args": {"s": "applepenapple", "wordDict": ["apple", "pen"]}, "expected": True},
        ],
        hidden=[{"args": {"s": "catsandog", "wordDict": ["cats", "dog", "sand", "and", "cat"]}, "expected": False}],
    )
    P(
        id="house-robber-iii",
        title="House Robber III",
        difficulty="medium",
        tags=["Tree", "DP"],
        unitId="unit-09",
        kind="stretch",
        order=7,
        microsoftNote="Tree DP: return (rob_this, skip_this) from each node.",
        statement="Houses form a binary tree. If you rob a node you cannot rob its children. Return the maximum amount of money you can rob.",
        examples=[{"input": "root = [3,2,3,null,3,null,1]", "output": "7"}],
        constraints=["The number of nodes is in [1, 10^4].", "0 <= Node.val <= 10^4"],
        followUp=None,
        editorial="Each node returns [take, skip]. take = val + skipL + skipR. skip = max(takeL,skipL)+max(takeR,skipR).",
        entry="rob",
        paramNames=["root"],
        helpers=["json", "tree"],
        py_params=[("root", "Optional[TreeNode]")],
        py_ret="int",
        js_params=[("root", "TreeNode|null")],
        js_ret="number",
        visible=[{"args": {"root": [3, 2, 3, None, 3, None, 1]}, "expected": 7}],
        hidden=[{"args": {"root": [3, 4, 5, 1, 3, None, 1]}, "expected": 9}],
    )


def write_unit10() -> None:
    P(
        id="lru-cache",
        title="LRU Cache",
        difficulty="medium",
        tags=["Design", "Hash Map", "Linked List"],
        unitId="unit-10",
        kind="core",
        order=1,
        microsoftNote="Hash + doubly linked list. O(1) get/put. Design round adjacent.",
        statement="Design a data structure that follows the constraints of a **Least Recently Used (LRU) cache**.\n\nImplement `LRUCache`:\n\n- `LRUCache(int capacity)` initialize with positive size.\n- `int get(int key)` return the value if present, else `-1`.\n- `void put(int key, int value)` update or insert. If the number of keys exceeds capacity, evict the least recently used key.\n\nGet and put must both be O(1) average.",
        examples=[{"input": '["LRUCache","put","put","get","put","get","put","get","get","get"]\\n[[2],[1,1],[2,2],[1],[3,3],[2],[4,4],[1],[3],[4]]', "output": "[null,null,null,1,null,-1,null,-1,3,4]"}],
        constraints=["1 <= capacity <= 3000", "0 <= key <= 10^4", "0 <= value <= 10^5", "At most 2 * 10^5 calls to get and put."],
        followUp=None,
        editorial="Map key → node. Dummy head/tail. Move to head on get/put. Evict tail.prev.",
        entry="LRUCache",
        paramNames=[],
        helpers=["json"],
        py_params=[],
        py_ret="None",
        js_params=[],
        js_ret="void",
        mode="class",
        starter_py="class LRUCache:\n    def __init__(self, capacity: int):\n        pass\n\n    def get(self, key: int) -> int:\n        pass\n\n    def put(self, key: int, value: int) -> None:\n        pass\n",
        starter_js="var LRUCache = function(capacity) {\n    \n};\n\n/** \n * @param {number} key\n * @return {number}\n */\nLRUCache.prototype.get = function(key) {\n    \n};\n\n/** \n * @param {number} key \n * @param {number} value\n * @return {void}\n */\nLRUCache.prototype.put = function(key, value) {\n    \n};\n",
        visible=[{
            "ops": [["LRUCache", 2], ["put", 1, 1], ["put", 2, 2], ["get", 1], ["put", 3, 3], ["get", 2], ["put", 4, 4], ["get", 1], ["get", 3], ["get", 4]],
            "expected": [None, None, None, 1, None, -1, None, -1, 3, 4],
        }],
        hidden=[{
            "ops": [["LRUCache", 1], ["put", 2, 1], ["get", 2]],
            "expected": [None, None, 1],
        }],
    )
    P(
        id="implement-trie",
        title="Implement Trie (Prefix Tree)",
        difficulty="medium",
        tags=["Design", "Trie"],
        unitId="unit-10",
        kind="core",
        order=2,
        microsoftNote="Node with children map and is_word flag.",
        statement="Implement a trie with `insert(word)`, `search(word)`, and `startsWith(prefix)`.\n\n`search` returns true only for a full word. `startsWith` is a prefix query.",
        examples=[{"input": '["Trie","insert","search","search","startsWith","insert","search"]\\n[[],["apple"],["apple"],["app"],["app"],["app"],["app"]]', "output": "[null,null,true,false,true,null,true]"}],
        constraints=["1 <= word.length, prefix.length <= 2000", "word and prefix consist of lowercase English letters.", "At most 3 * 10^4 calls."],
        followUp=None,
        editorial="Each node: dict child, bool end. Walk characters.",
        entry="Trie",
        paramNames=[],
        helpers=["json"],
        py_params=[],
        py_ret="None",
        js_params=[],
        js_ret="void",
        mode="class",
        starter_py="class Trie:\n    def __init__(self):\n        pass\n\n    def insert(self, word: str) -> None:\n        pass\n\n    def search(self, word: str) -> bool:\n        pass\n\n    def startsWith(self, prefix: str) -> bool:\n        pass\n",
        starter_js="var Trie = function() {\n    \n};\n\nTrie.prototype.insert = function(word) {\n    \n};\n\nTrie.prototype.search = function(word) {\n    \n};\n\nTrie.prototype.startsWith = function(prefix) {\n    \n};\n",
        visible=[{
            "ops": [["Trie"], ["insert", "apple"], ["search", "apple"], ["search", "app"], ["startsWith", "app"], ["insert", "app"], ["search", "app"]],
            "expected": [None, None, True, False, True, None, True],
        }],
        hidden=[{
            "ops": [["Trie"], ["insert", "a"], ["search", "a"], ["startsWith", "a"]],
            "expected": [None, None, True, True],
        }],
    )
    P(
        id="sliding-window-maximum",
        title="Sliding Window Maximum",
        difficulty="hard",
        tags=["Deque", "Sliding Window"],
        unitId="unit-10",
        kind="core",
        order=3,
        microsoftNote="Monotonic deque of indices. Hard but pattern-based.",
        statement="You are given an array `nums` and a sliding window of size `k` moving from the very left to the very right. Return the max of each window.",
        examples=[{"input": "nums = [1,3,-1,-3,5,3,6,7], k = 3", "output": "[3,3,5,5,6,7]"}],
        constraints=["1 <= nums.length <= 10^5", "-10^4 <= nums[i] <= 10^4", "1 <= k <= nums.length"],
        followUp="O(n) with a deque.",
        editorial="Deque stores indices in decreasing nums value. Pop back smaller, pop front out of window. Front is max.",
        entry="maxSlidingWindow",
        paramNames=["nums", "k"],
        helpers=["json", "json", "json"],
        py_params=[("nums", "list[int]"), ("k", "int")],
        py_ret="list[int]",
        js_params=[("nums", "number[]"), ("k", "number")],
        js_ret="number[]",
        visible=[{"args": {"nums": [1, 3, -1, -3, 5, 3, 6, 7], "k": 3}, "expected": [3, 3, 5, 5, 6, 7]}],
        hidden=[{"args": {"nums": [1], "k": 1}, "expected": [1]}, {"args": {"nums": [9, 8, 7, 6], "k": 2}, "expected": [9, 8, 7]}],
    )
    P(
        id="trapping-rain-water",
        title="Trapping Rain Water",
        difficulty="hard",
        tags=["Array", "Two Pointers", "Stack"],
        unitId="unit-10",
        kind="core",
        order=4,
        microsoftNote="Two-pointer water. Interview-hard that is still pattern-based.",
        statement="Given `n` non-negative integers representing an elevation map where the width of each bar is `1`, compute how much water it can trap after raining.",
        examples=[{"input": "height = [0,1,0,2,1,0,1,3,2,1,2,1]", "output": "6"}],
        constraints=["n == height.length", "1 <= n <= 2 * 10^4", "0 <= height[i] <= 10^5"],
        followUp="O(1) extra space two pointers.",
        editorial="left/right pointers, left_max/right_max. Water at a cell = min(left_max,right_max) - height. Move the side with smaller max.",
        entry="trap",
        paramNames=["height"],
        helpers=["json", "json"],
        py_params=[("height", "list[int]")],
        py_ret="int",
        js_params=[("height", "number[]")],
        js_ret="number",
        visible=[
            {"args": {"height": [0, 1, 0, 2, 1, 0, 1, 3, 2, 1, 2, 1]}, "expected": 6},
            {"args": {"height": [4, 2, 0, 3, 2, 5]}, "expected": 9},
        ],
        hidden=[{"args": {"height": [4, 2, 3]}, "expected": 1}],
    )
    P(
        id="merge-k-sorted-lists",
        title="Merge k Sorted Lists",
        difficulty="hard",
        tags=["Linked List", "Heap"],
        unitId="unit-10",
        kind="stretch",
        order=5,
        microsoftNote="Min-heap of k heads, or divide-and-conquer merge.",
        statement="You are given an array of `k` linked-lists `lists`, each sorted in ascending order. Merge all the linked-lists into one sorted linked-list and return it.",
        examples=[{"input": "lists = [[1,4,5],[1,3,4],[2,6]]", "output": "[1,1,2,3,4,4,5,6]"}],
        constraints=["k == lists.length", "0 <= k <= 10^4", "0 <= lists[i].length <= 500", "-10^4 <= Node.val <= 10^4", "lists[i] is sorted.", "The sum of lists[i].length <= 10^4"],
        followUp="O(n log k).",
        editorial="Heap of (val, node) for each list head. Pop min, push next.",
        entry="mergeKLists",
        paramNames=["lists"],
        helpers=["list", "listlist"],
        py_params=[("lists", "list[Optional[ListNode]]")],
        py_ret="Optional[ListNode]",
        js_params=[("lists", "Array<ListNode|null>")],
        js_ret="ListNode|null",
        visible=[{"args": {"lists": [[1, 4, 5], [1, 3, 4], [2, 6]]}, "expected": [1, 1, 2, 3, 4, 4, 5, 6]}],
        hidden=[
            {"args": {"lists": []}, "expected": []},
            {"args": {"lists": [[]]}, "expected": []},
        ],
    )


if __name__ == "__main__":
    main()
